### ISSUE TITLE
Corpses impede characters movement [C]

### ISSUE THREAD

**Issue by J-Nunes** [traguill/SummerProject2#24]
**Class**: Major
**Type**: Gameplay
**Frequency**: 100%
**Steps**: 
- Select Nyx.
- Kill an enemy without bein discovered.
- Try to go with Nyx at the other side of the corpse (in front).

**Result**: The corpse impede Nyx movement and this makes the mobility so difficult.
**Expected result**: Corpses don't have a collider that impedes characters' movement.

**Comment by traguill** [comment]
@J-Nunes The result shouldn't be that the corpses don't have a collider. In this case should be that the pathfinding should ignore the corpses as obstacles. If we eliminate the colliders Barion will not be able to pick up the corpses
