### ISSUE TITLE
Barion's shield makes invisible [C]

### ISSUE THREAD

**Issue by J-Nunes** [traguill/SummerProject2#25]
**Class**: Minor
**Type**: Visual
**Frequency**: 100%
**Steps**: 
- Select Barion.
- Press W (doesn't matter the direction of the shield).
- Keep pressing UP_ARROW, until Barion is in the lower part of the screen.

**Result**: Barion's shield makes partially invisible (caused by camera angle, too much elevetate it, I guess)
**Expected result**: Barion's shield should be always visible during the ability.

**Comment by traguill** [comment]
Looks good for me
